language: go

go:
  - "1.12.5"

env:
  - GO111MODULE=on

os:
  - linux
  - osx

notifications:
  email: false

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - golangci-lint run
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - go build -o objectmap -mod=vendor -ldflags "-s -w" cmd/objectmap/objectmap.go && ./objectmap

after_success:
  - bash <(curl -s https://codecov.io/bash)